name: mlflow-project
channels:
  - conda-forge
dependencies:
  - python=3.7 
  - pip
  - pip:
      - cloudpickle
      - matplotlib
      - mlflow
      - numpy
      - nltk
      - pandas
      - pyarrow
      - scikit-learn
      - scipy
